// examples/react-example-webapp/src/pages/signingComponent.tsx
import {useState} from "react";
import {signPrescription, HubResponse} from "nhs-credential-manager-prescription-signing";
import {Base64} from "js-base64";

export default function SigningComponent() {

    const initialJson  = {
        algorithm: "RS1",
        requestType: 1,
        version: 1,
        flags: 0,
        payloads: [
            {
                id: "123",
                payload: "Some Payload"
            }
        ]
    };

    const [payload, setPayload] = useState("");
    const [json, setJson] = useState("");
    const [base64Json, setBase64Json] = useState("");
    const [result, setResult] = useState("");
    const [error, setError] = useState("");

    function signJson() {
        signPrescription(base64Json).then((result: HubResponse) => setResult(JSON.stringify(result,null,'\t'))).catch(e => {
            console.error(e)
            setError(e.message)
        });
    }

    return <>
        <label htmlFor={"payload"}>Payload:</label>
        <input id={"payload"} value={payload} onChange={inputEvent => {
            setPayload(inputEvent.target.value);
            let intermediateJson = initialJson;
            intermediateJson.payloads[0].payload = inputEvent.target.value;
            setJson(JSON.stringify(intermediateJson, null, '\t'));
            setBase64Json(Base64.encode(JSON.stringify(intermediateJson)));
        }}/>
        <label htmlFor={"json"}>JSON:</label>
        <textarea id={"json"} value={json} onChange={inputEvent => {
            setJson(inputEvent.target.value);
            setBase64Json(Base64.encode(JSON.stringify(inputEvent.target.value, null, '\t')));
            setPayload(JSON.parse(inputEvent.target.value).payloads[0].payload);
        }}/>
        <label htmlFor={"base64Json"}>Base64 Encoded JSON:</label>
        <textarea id={"base64Json"} value={base64Json} onChange={inputEvent => {
            setBase64Json(inputEvent.target.value);
            setJson(Base64.decode(inputEvent.target.value));
            setPayload(JSON.parse(Base64.decode(inputEvent.target.value)).payloads[0].payload);
        }}/>
        <button onClick={() => signJson()}>Submit</button>
        <pre style={{
            maxWidth: "80%",
            overflow: "scroll"
        }}>{result}</pre>
        <div>{error}</div>
    </>;
}

// examples/vue-js-example-webapp/src/components/SigningComponent.vue
<script setup>
import {reactive} from "vue";
import {Base64} from "js-base64";
import {signPrescription} from "nhs-credential-manager-prescription-signing";

const initialJson = {
  algorithm: "RS1",
  requestType: 1,
  version: 1,
  flags: 0,
  payloads: [
    {
      id: "123",
      payload: "Some Payload"
    }
  ]
};
const state = reactive({
  payload: "",
  json: JSON.stringify(initialJson, null, "\t"),
  base64Json: Base64.encode(JSON.stringify(initialJson)),
  result: "",
  errorMessage: ""
});

function payloadChange(event) {
  state.payload = event.target.value;
  let intermediateJson = initialJson;
  intermediateJson.payloads[0].payload = event.target.value;
  state.json = JSON.stringify(intermediateJson, null, "\t");
  state.base64Json = Base64.encode(JSON.stringify(intermediateJson));
}

function jsonChange(event) {
  state.json = event.target.value;
  state.base64Json = Base64.encode(JSON.stringify(event.target.value, null, "\t"));
  state.payload = JSON.parse(event.target.value).payloads[0].payload;
}

function base64Change(event) {
  state.base64Json = event.target.value;
  state.json = Base64.decode(event.target.value);
  state.payload = JSON.parse(Base64.decode(event.target.value)).payloads[0].payload;
}

function signJson() {
  signPrescription(state.base64Json).then((result) => state.result = JSON.stringify(result, null, "\t")).catch(e => {
    console.error(e);
    state.errorMessage = e.message;
  });
}
</script>

<template>
  <div>
    <div>
      <label for="payload">Payload:</label>
    </div>
    <div>
      <input id="payload" v-model="state.payload" @change="payloadChange"/>
    </div>
  </div>

  <div>
    <div>
      <label for="json">JSON:</label>
    </div>
    <div>
      <textarea id="json" v-model="state.json" @change="jsonChange"/>
    </div>
  </div>

  <div>
    <div>
      <label for="base64Json">Base64 Encoded JSON:</label>
    </div>
    <div>
      <textarea id="base64Json" v-model="state.base64Json" @change="base64Change"/>
    </div>
  </div>

  <div>
    <button @click="signJson">Submit</button>
  </div>

  <div>{{ state.result }}</div>
  <div>{{ state.errorMessage }}</div>
</template>
